EPS-4: create database schema
IFortexJavaLab/eps-semeynikov-andrey-java-1 pull request #1
Opened 2024-10-23 08:43 UTC by AndreySemeynikovIF

[JIRA-4](https://ifortex-team-java1.atlassian.net/browse/EPS-4) 
Created db schema, added docker-compose with initial sql script to start container with db. Script creates tables, insert values

2024-10-23 09:11 UTC, PavelShynkarou requested changes
Look like your task EPS-4 in the wrong state now. Could you please fix it?

2024-10-23 09:11 UTC, PavelShynkarou commented on docker-compose/db-init/V1__initial.sql
> +    price                   REAL         NOT NULL,
FYI, REAL datatype for prices in DB is generally not recommended due to potential issues with precision and rounding, because they represent numbers in binary format. This can lead to inaccuracies when performing arithmetic operations on prices. As an alternative I would to recommend to use DECIMAL(*, *).

2024-10-23 09:11 UTC, PavelShynkarou commented on docker-compose/db-init/V1__initial.sql
> +    start_date              TIMESTAMP,
Not sure about it. Could you explain why start_date can be null? How I know when it starts?

2024-10-23 09:11 UTC, PavelShynkarou commented on docker-compose/db-init/V1__initial.sql
> +WITH gen_courses AS (
Did you test it, does it work properly?

2024-10-23 13:59 UTC, AndreySemeynikovIF commented on docker-compose/db-init/V1__initial.sql
> +    start_date              TIMESTAMP,
Let us suppose that on some course enrolled only 15 people. This course is closed because of requirements of minimal number of people. So, it means this course won't start before more people will be enrolled. If a course is closed and there are not enough people, we don't know when a course will start. It means start_date can be null.
There is another business logic where courses aren't dependent on number of people. Course will start according to start_date. Of course in this case start_date should be not null.

What logic should i implement?

2024-10-23 14:13 UTC, AndreySemeynikovIF commented on docker-compose/db-init/V1__initial.sql
> +WITH gen_courses AS (
yes, it is works properly. But there is thing: on each course will be the same number of students. Function `LIMIT 30 + (random() * 21)::int` will work only once for the whole select. It can be a bug, it can be a feature)

2024-10-24 08:27 UTC, AndreySemeynikovIF commented on docker-compose/db-init/V1__initial.sql
> +    price                   REAL         NOT NULL,
Got it, will be fixed

2024-10-24 08:34 UTC, AndreySemeynikovIF commented on docker-compose/db-init/V1__initial.sql
> +WITH gen_courses AS (
I tested before commit, it works properly but there is a thing. According to my logic some students will be enrolled on MANY courses, and some won't be enrolled at all. Also each course has the same number of people because function `LIMIT 30 + (random() * 21)::int` will be called only once. I rewrite this function to be more simple and not so random.

2024-10-24 09:07 UTC, AndreySemeynikovIF commented
> Look like your task EPS-4 in the wrong state now. Could you please fix it?

Fixed. I added comment to the task in jira

2024-10-24 09:16 UTC, PavelShynkarou commented on docker-compose/db-init/V1__initial.sql
> +    start_date              TIMESTAMP,
> Let us suppose that on some course enrolled only 15 people. This course is closed because of requirements of minimal number of people.

I've created a course without start_date. And during one year after creation 15 students joined. And it still opened. Why? Because there is no start_date time. Only conjunction of the quantity of students joined till start_date can solve condition - course should be closed because till start_date we have not achieved min quantity in students. But pay attention that this condition should be solved on the backend.

2024-10-24 09:25 UTC, AndreySemeynikovIF commented on docker-compose/db-init/V1__initial.sql
> +    start_date              TIMESTAMP,
fixed, added not null to this field

2024-10-24 09:27 UTC, PavelShynkarou approved these changes
LGTM! Great start!

2024-10-24 09:53 UTC, vladqf approved these changes
Approved

2024-10-24 11:53 UTC, vladqf approved these changes

2024-10-24 11:58 UTC, merged