JIRA-5: Create entities and database setup
IFortexJavaLab/eps-semeynikov-andrey-java-1 pull request #2
Opened 2024-10-28 18:54 UTC by AndreySemeynikovIF

[JIRA-5](https://ifortex-team-java1.atlassian.net/browse/EPS-5). Setup project, add configuration files. Added Student and Course model classes. Define db connection and setup migration script using flyway. Added stylsih changes into sql script and and moved it to the resources package.

2024-10-28 18:59 UTC, vladqf commented
pom.xml file is missing

2024-10-29 17:02 UTC, PavelShynkarou requested changes

2024-10-29 17:02 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/config/MyWebApplicationInitializer.java
> +public class MyWebApplicationInitializer implements WebApplicationInitializer {
Looks like we figured out that this class unnecessarily.

2024-10-29 17:02 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/model/Student.java
> +import lombok.*;
Could you please fix it?

2024-10-29 22:13 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/config/MyWebApplicationInitializer.java
> +public class MyWebApplicationInitializer implements WebApplicationInitializer {
yep, deleted it.

2024-10-29 22:15 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/model/Student.java
> +import lombok.*;
fixed. Also changed the setting in IDEA to prevent such case in the future.

2024-10-30 06:15 UTC, PavelShynkarou approved these changes

2024-10-30 09:01 UTC, vladqf approved these changes

2024-10-30 22:28 UTC, merged