Jira-14: Define dao
IFortexJavaLab/eps-semeynikov-andrey-java-1 pull request #3
Opened 2024-11-02 20:49 UTC by AndreySemeynikovIF

[Jira-14](https://ifortex-team-java1.atlassian.net/browse/EPS-14). 
Defined CourseDao and StudentDao with required functions. Added formatting for json serialization and deserialization. Fixed some typo and types inaccuracies.

2024-11-03 15:52 UTC, PavelShynkarou requested changes

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAO.java
> +package com.ifortex.internship.DAO;
Holy Moly! Please familiarise with [conversion](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) of the package naming.
Lets create impl subpackage and put all implementations inside.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAO.java
> +  void create(Course course);
Please provide JavaDocs for all methods.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    if (course.isPresent()) {
What do you think? 

`return course.map(c -> {
    c.setStudentSet(students);
    return c;
});`

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    List<Course> courses = jdbcTemplate.query(sql, new CourseRowMapper());
Why do you use new mapper here, if it presents as a field already?

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    for (Course course : courses) {
Please avoid for.. and other loops. Try to use functional style.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    String sql = "SELECT * FROM course WHERE id = ?";
The main idea is extract course with students with just 1 sql query! Here you do 2 queries, it is overhead. Please fix it here and other places where you do redundant query.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/StudentDAO.java
> +  void create(Student student);
Please provide JavaDocs for all methods.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +  private final RowMapper<Course> courseRowMapper = new CourseRowMapper();
Looks like we use Spring and new operator is not acceptable. Please fix it. Use DI.

2024-11-03 15:52 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +        "UPDATE course SET name = ?, description = ?, price = ?, duration = ?, start_date = ?, last_update_date = ?, course_status = ?::course_status  WHERE id = ?";
My question is if I want to add or delete students to/from course, how it will be handled?  
And did you considered the case when I will pass only 1 field for update? For example description. In your implementation other fields will be or null or 0, in this case exception will be thrown.

2024-11-03 20:19 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAO.java
> +package com.ifortex.internship.DAO;
will be fixed

2024-11-03 20:24 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    if (course.isPresent()) {
it makes sense

2024-11-03 20:43 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    String sql = "SELECT * FROM course WHERE id = ?";
I understand the idea but have some diffuculties with implementation. Now I have rowMappers for course and student. If i will use query like this

```
SELECT
    c.id AS course_id,
    c.name AS course_name,
    c.description AS course_description,
    c.price AS course_price,
    c.duration AS course_duration,
    c.start_date AS course_start_date,
    c.last_update_date AS course_last_update_date,
    c.course_status AS course_status,
    s.id AS student_id,
    s.name AS student_name
FROM
    course c
        LEFT JOIN
    course_student cs ON c.id = cs.course_id
        LEFT JOIN
    student s ON cs.student_id = s.id
WHERE
    c.id = ?;
```

I should write new rowMapper for this query. Is it normal to have many rowMappers for different sql queries? Should I declare rowMappers in the separate java class like I did or decalre it in the dao class for example like Vlad did?

 ```
private final RowMapper<Course> courseRowMapper =
      ((rs, rowNum) ->
          Course.builder()
              .id(rs.getInt("id"))
              .name(rs.getString("name"))
              .description(rs.getString("description"))
              .price(new BigDecimal(rs.getString("price")))
              .duration(rs.getInt("duration"))
              .startDate(LocalDateTime.parse(rs.getString("start_date"), dateTimeFormatter))
              .lastUpdateDate(
                  LocalDateTime.parse(rs.getString("last_update_date"), dateTimeFormatter))
              .isOpen(rs.getBoolean("is_open"))
              .students(new HashSet<>())
              .build());
```

2024-11-03 20:44 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    List<Course> courses = jdbcTemplate.query(sql, new CourseRowMapper());
My bad, will be fixed

2024-11-03 21:02 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +        "UPDATE course SET name = ?, description = ?, price = ?, duration = ?, start_date = ?, last_update_date = ?, course_status = ?::course_status  WHERE id = ?";
Enrollments and removal student on course will be handling via different method that will be implemented. Updating course means update only fileds like name, description and not students as i see it. There is no problem at all, I can change my logic and update students using update method in courseDao.

2024-11-03 21:12 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +        "UPDATE course SET name = ?, description = ?, price = ?, duration = ?, start_date = ?, last_update_date = ?, course_status = ?::course_status  WHERE id = ?";
> And did you considered the case when I will pass only 1 field for update?

It works fine. I use such code in service to check data in dto and update provided fileds.

```
Course course =
        courseDAO.find(id).orElseThrow(() -> new ResourceNotFoundException("Course not found", id));
    if (courseDTO.getName() != null) course.setName(courseDTO.getName());
    if (courseDTO.getDescription() != null) course.setDescription(courseDTO.getDescription());
    if (courseDTO.getPrice() != null) course.setPrice(courseDTO.getPrice());
    if (courseDTO.getDuration() != 0) course.setDuration(courseDTO.getDuration());
    if (courseDTO.getStartDate() != null) course.setStartDate(courseDTO.getStartDate());

    courseDAO.update(course)
```
If there are better ways to handle this query I am ready to change it.

![image_2024-11-03_23-55-32](https://github.com/user-attachments/assets/421796bf-e0e7-47f7-aa75-f7603ab6f88a)

![photo_2024-11-04_00-04-27](https://github.com/user-attachments/assets/5440c6ee-15cc-4174-b539-f3ddfcbe1215)

![image_2024-11-03_23-56-50](https://github.com/user-attachments/assets/5330accf-295e-4d74-af36-9b0364b86fca)

2024-11-04 07:43 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    String sql = "SELECT * FROM course WHERE id = ?";
You need Course, Student and maybe one more mapper that will be use both other mapper.

2024-11-04 07:58 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +        "UPDATE course SET name = ?, description = ?, price = ?, duration = ?, start_date = ?, last_update_date = ?, course_status = ?::course_status  WHERE id = ?";
This approach is not appropriate. You should update only fields that were updated. This approach will be more efficient, as it reduces the update payload. It also avoids overwriting fields that weren’t meant to change.

And please provide more details about editing students in the course. How and where it will be implemented? As long as I can see it should be implemented here

2024-11-04 08:29 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAO.java
> +  void create(Course course);
fixed

2024-11-04 08:30 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/StudentDAO.java
> +  void create(Student student);
fixed

2024-11-05 10:01 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +  private final RowMapper<Course> courseRowMapper = new CourseRowMapper();
fixed

2024-11-05 10:02 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    String sql = "SELECT * FROM course WHERE id = ?";
fixed. Implemented ResultSetExtractor for the query with course and students

2024-11-05 10:02 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    for (Course course : courses) {
fixed

2024-11-05 10:04 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/DAO/CourseDAOImpl.java
> +    for (Course course : courses) {
can I use forEach instead?

2024-11-05 12:29 UTC, PavelShynkarou requested changes

2024-11-05 12:29 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/dao/impl/CourseDaoImpl.java
> +            + "JOIN course_student cs ON c.id = cs.course_id "
Looks like in this case Course without students will be missed. It is not expected behaviour

2024-11-05 12:29 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/dao/impl/CourseDaoImpl.java
> +    sql.setLength(sql.length() - 2);
Why do you do this? It is for removing last comma and space? Please use String.join() method or StringJoiner

2024-11-05 12:29 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/dao/impl/StudentDaoImpl.java
> +    sql.setLength(sql.length() - 2);
the same

2024-11-05 12:29 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +public class CourseDto {
Why these Dtos here? Looks like it should be differed in [this](https://ifortex-team-java1.atlassian.net/browse/EPS-8) ticket?

2024-11-06 07:28 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +public class CourseDto {
Created it for checking in the controller and added it to commit by mistake

2024-11-07 09:31 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dao/impl/CourseDaoImpl.java
> +  public CourseDaoImpl(
fixed

2024-11-07 09:31 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dao/impl/StudentDaoImpl.java
> +    sql.setLength(sql.length() - 2);
fixed

2024-11-07 09:43 UTC, PavelShynkarou approved these changes

2024-11-07 09:43 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/dao/impl/CourseDaoImpl.java
> +          if ("course_status".equals(field)) setClauses.add(field + " = ?::course_status");
Please don't skimp on the parentheses next time)

2024-11-07 14:14 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dao/impl/CourseDaoImpl.java
> +          if ("course_status".equals(field)) setClauses.add(field + " = ?::course_status");
got it

2024-11-07 14:50 UTC, vladqf approved these changes

2024-11-07 19:39 UTC, merged