EPS-15: Define services
IFortexJavaLab/eps-semeynikov-andrey-java-1 pull request #4
Opened 2024-11-14 23:49 UTC by AndreySemeynikovIF

[JIRA-15](https://ifortex-team-java1.atlassian.net/browse/EPS-15)

- Created StudentService and CourseService interfaces and their implementations,
- Implemented CRUD operations for Course and Student entities,
- Created DTOs, mappers, implemented validations for each DTO,
- Added custom exceptions, GlobalExceptionHandler to catch them, custom error codes,
- Added scheduler that checks and changes course status if necessary once a day,
- Implemented checks for the all business constraints.

2024-11-15 10:18 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +      course.setLastUpdateDate(LocalDateTime.now());
What if getUpdates() is empty? Will lastUpdateDate be handled in a correct way? If i pass lastUpdateDate during update request, will it be ignored?

2024-11-15 19:21 UTC, PavelShynkarou requested changes

2024-11-15 19:21 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    if (studentIds.stream().anyMatch(id -> id == null || id <= 0)) {
Please check my comment above. Provide boolean variable here

2024-11-15 19:21 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    List<StudentDto> students = studentIds.stream().map(studentService::find).toList();
The same. This approach not applicable. Refactor it

2024-11-15 19:21 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/impl/StudentServiceImpl.java
> +    return StudentToStudentDtoMapper.convert(student);
Formatting lost here

2024-11-15 19:21 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/config/AppConfig.java
> +    return new LocalValidatorFactoryBean();
Did you try to put LocalValidatorFactoryBean as method parameter and return it into the body?

2024-11-15 21:43 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +  private LocalDateTime lastUpdateDate;
In my opinion users should see lastUpdateDate. If there is no need I can ignore it

2024-11-15 21:46 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +      message = "Duration must be less than 365 days",
I needed upper bound for this field and I decide that duration limit can be 1 year. It wasn't in the requirements to the project.  If there is other logic, please, provide it to me

2024-11-15 21:52 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseUpdateDto.java
> +public class CourseUpdateDto {
This class is used in the update method in the CourseService to create map with fields and values which needed to be updated. Maybe it is overhead to create a class for this task.
I will refactor update method without using of this class

2024-11-15 21:52 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/StudentUpdateDto.java
> +public class StudentUpdateDto {
Explained in previous comment

2024-11-15 22:04 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/exception/custom/CourseDtoValidationException.java
> +    super(ErrorCode.COURSE_DTO_VALIDATION_FAILED.getDefaultMessage());
According to the [jakarta documentation](https://javadoc.io/doc/jakarta.validation/jakarta.validation-api/latest/jakarta/validation/Validator.html) method validate of validator return Set of ConstraintViolation. It is because I use it to get all validation errors. 
At this time I do not know of any other standard implementation. Will be thankfull for providing other approaches.

2024-11-15 22:18 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    List<StudentDto> students = studentIds.stream().map(studentService::find).toList();
Yes there will be studentIds.size() calls to the db to check if provided students ids are real. How can i check if a student exists in a db without call to a db? I have no idea how to implement check student by id without call to a db. Please help me to figure it out

2024-11-15 22:25 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/StudentServiceImpl.java
> +    return StudentToStudentDtoMapper.convert(student);
Formatting isn't lost. It is a standart google java format.

![Снимок экрана 2024-11-16 012438](https://github.com/user-attachments/assets/3b874ac5-1b10-4116-81f5-3ff015a9e6de)

2024-11-15 22:27 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/StudentServiceImpl.java
> +    return StudentToStudentDtoMapper.convert(student);
Formatting isn't lost. It is a standart google java formatter.
![Снимок экрана 2024-11-16 012438](https://github.com/user-attachments/assets/12c05ce3-d481-4c91-a9a0-ccbf3c008454)

2024-11-15 22:38 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/config/AppConfig.java
> +    return new LocalValidatorFactoryBean();
I am not sure that i understand you correctly. Something like that?
sorry for strange formatting)

@ Bean
public LocalValidatorFactoryBean validator(LocalValidatorFactoryBean localValidatorFactoryBean ) {
return localValidatorFactoryBean;
}

Unfortunately[ constructor do not accept arguments](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/beanvalidation/LocalValidatorFactoryBean.html#%3Cinit%3E())

2024-11-16 00:38 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +  @JsonProperty("id")
Not really. Removed it.

2024-11-16 00:38 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseStudentUpdateDto.java
> +  long courseId;
fixed

2024-11-16 00:38 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseStudentUpdateDto.java
> +  @JsonProperty("courseId")
fixed

2024-11-16 00:40 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/StudentDto.java
> +  public boolean equals(Object object) {
fixed

2024-11-16 00:40 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/mapper/CourseDtoToCourseMapper.java
> +    return course;
fixed

2024-11-16 00:40 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/mapper/CourseDtoToCourseMapper.java
> +    Course course = new Course();
fixed

2024-11-16 00:43 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/mapper/CourseDtoToCourseMapper.java
> +public class CourseDtoToCourseMapper {
The only explanation is my inaccuracy)
Removed @ Component and made all functions static. 
Fixed

2024-11-16 00:43 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/mapper/CourseToCourseDtoMapper.java
> +  public static CourseDto convert(Course course) {
fixed

2024-11-16 00:44 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    if (course.getCourseStatus() != CourseStatus.OPENED)
fixed

2024-11-16 00:46 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/model/enumeration/CourseField.java
> +  private final String fieldName;
fixed

2024-11-16 00:46 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/model/enumeration/StudentField.java
> +  private final String fieldName;
fixed

2024-11-16 21:08 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    List<StudentDto> students = studentIds.stream().map(studentService::find).toList();
refactored

2024-11-16 21:08 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    if (studentIds.stream().anyMatch(id -> id == null || id <= 0)) {
fixed

2024-11-16 21:08 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    List<StudentDto> students = studentIds.stream().map(studentService::find).toList();
fixed

2024-11-16 21:12 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/markers/Create.java
> +public interface Create{}
didn't change my approach because of runnig out of time)

2024-11-16 21:16 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/CourseService.java
> +   * Retrieves all courses in the db.
got it, fixed

2024-11-16 21:37 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/CourseService.java
> + * updating, finding, and deleting courses, as well as enrolling and removing students from a
fixed

2024-11-16 21:37 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    if (courseDto.getName() != null) {
fixed

2024-11-16 21:37 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +    if (studentIds.stream().anyMatch(id -> id == null || id <= 0)) {
fixed

2024-11-17 13:29 UTC, PavelShynkarou approved these changes

2024-11-17 13:31 UTC, vladqf approved these changes

2024-11-18 06:22 UTC, merged